### get all users
GET http://localhost:5000/user/list


### delete user by fistname
DELETE http://localhost:5000/user/delete/ali


### register user
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "first_name" : "ali",
    "last_name" : "delbar",
    "nationalCode" : "5140066400",
    "password" : "1231234",
    "confirm_password" : "1231234",
    "phoneNumber" : "09367109094"
}


### login user
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "nationalCode" : "5140066400",
    "password" : "1231234"
}

### update user information
POST http://localhost:5000/user/update
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYXRpb25hbENvZGUiOiI1MTQxMjM0NTY3IiwiaWF0IjoxNjUzMDI3MjcxLCJleHAiOjE2NTczNDcyNzF9.1xqmpwJTfTjas-IyACwy2WFN_zMANAq7Hp_SLlP8uiU
Content-Type: application/json

{
    "dateOfBirth" : "21.01.1387",
    "father_name" : "davood", 
    "age" : 14,
    "email" : "omid.44@نخاشد.com",
    "address" : "KATE GONBAD"
}
